### ISSUE TITLE
React Router RoutingContext null

### ISSUE THREAD

**Issue by jonstuebe** [gaearon/babel-plugin-react-transform#69]
I'm getting an empty node when using this in regards to React Router. The Initial react render is happening, but the RoutingContext component is empty. Any ideas?

**Comment by thejameskyle** [comment]
This doesn't seem to be relevant to this repo at all. It's not actionable so closing...

**Comment by jonstuebe** [comment]
@thejameskyle should I post it on react router? It's a project used by most react devs and unless I'm wrong doesn't currently work with this transform tool which seems like a huge issue.

**Comment by thejameskyle** [comment]
Provide something that shows this babel plugin breaking react router and I'll reopen

**Comment by jonstuebe** [comment]
@thejameskyle https://github.com/jonstuebe/react-transform-boilerplate

**Comment by thejameskyle** [comment]
Okay... now can you make that a more reduced test case? Theres a whole lot of noise in that repo and I'm not going to go through all of it

**Comment by jonstuebe** [comment]
The specific command is `npm start`. I stripped down most of the code so it's really just the <RouterContainer> being rendered with only one component inside of it: <App>. All the rest of the code in the repo hasn't been touched.

**Comment by gaearon** [comment]
The problem in your code is incorrect usage of `import` and `export`.
You use `export default` for `App` and `RouterContainer`, but later you use named imports:

```js
// RouterContainer.js
// import { App } from './App'; <--- wrong way to import a default export
import App from './App'; // <--- what it should be

// index.js
// import { RouterContainer } from './RouterContainer'; <--- wrong way to import a default export
import RouterContainer from './RouterContainer'; // <--- what it should be
```

[This is a very good guide](http://www.2ality.com/2014/09/es6-modules-final.html) explaining the difference between default and named exports.

That said I don't quite understand why this issue was filed in this repository. If you turn off this Babel plugin the issue stays exactly the same. Therefore it's unrelated, and it would've been best to ask on StackOverflow rather than in an unrelated repository. :-)

I hope this helps!

**Comment by jonstuebe** [comment]
Makes sense. Thanks!
