### ISSUE TITLE
Can we have superClass Regexp matching option , for inheritance ?

### ISSUE THREAD

**Issue by singggum3b** [gaearon/babel-plugin-react-transform#93]
People go all hype about composition over inheritance, but for a simple master page template , i still find inheritance better addressing the issue.
```
class ComponentMaster extends React.Component {}

class ComponentIndex extends ComponentMaster {}

```

One problem is babel react-transform only allow fixed superClass name.
So,can we have superClass Regexp matching option , for inheritance ? like `/^Component/`

**Comment by singggum3b** [comment]
i opened a PR for this [https://github.com/gaearon/babel-plugin-react-transform/pull/94](url)

**Comment by gaearon** [comment]
This project is getting deprecated in favor of [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
Since it doesn’t need to “detect” components at all, this is no longer necessary.

[Check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61)!

I don’t plan to add new features to this project so I’m closing.
